### ISSUE TITLE
Problem to install dependencies

### ISSUE THREAD

**Issue by joavilati** [icerockdev/moko-mvvm#102]
I am trying to install some moko dependencies and getting this error.

org.gradle.internal.resolve.ArtifactNotFoundException: Could not find mvvm-livedata-0.9.1-samplessources.jar (dev.icerock.moko:mvvm-livedata:0.9.1).
Searched in the following locations:
    https://dl.bintray.com/icerockdev/moko/dev/icerock/moko/mvvm-livedata/0.9.1/mvvm-livedata-0.9.1-samplessources.jar

it looks like the "-samplessources" part of the link shouldn't be there, but a don't know how to remove it.

![image](https://user-images.githubusercontent.com/48884950/105756756-cc415c00-5f2b-11eb-8dff-00aecb8c6627.png)

![image](https://user-images.githubusercontent.com/48884950/105756816-e3804980-5f2b-11eb-9953-dc456565a329.png)

**Comment by Alex009** [comment]
Hi! Can you run `./gradlew build` from terminal and copy all output?

**Comment by joavilati** [comment]
> No matching variant of dev.icerock.moko:mvvm-core:0.9.1 was found. The consumer was configured to find an API of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
          - Variant 'commonMainMetadataElements-published' capability dev.icerock.moko:mvvm-core:0.9.1:
              - Incompatible because this component declares a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'common' and the consumer needed an API of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
          - Variant 'debugApiElements-published' capability dev.icerock.moko:mvvm-core:0.9.1 declares an API of a component:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
          - Variant 'debugRuntimeElements-published' capability dev.icerock.moko:mvvm-core:0.9.1 declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
          - Variant 'iosArm64ApiElements-published' capability dev.icerock.moko:mvvm-core:0.9.1:
              - Incompatible because this component declares a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed an API of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
          - Variant 'iosArm64MetadataElements-published' capability dev.icerock.moko:mvvm-core:0.9.1:
              - Incompatible because this component declares a usage of 'kotlin-metadata' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed an API of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
          - Variant 'iosX64ApiElements-published' capability dev.icerock.moko:mvvm-core:0.9.1:
              - Incompatible because this component declares a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed an API of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
          - Variant 'iosX64MetadataElements-published' capability dev.icerock.moko:mvvm-core:0.9.1:
              - Incompatible because this component declares a usage of 'kotlin-metadata' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed an API of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
          - Variant 'metadataApiElements-published' capability dev.icerock.moko:mvvm-core:0.9.1:
              - Incompatible because this component declares a usage of 'kotlin-metadata' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'common' and the consumer needed an API of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
          - Variant 'releaseApiElements-published' capability dev.icerock.moko:mvvm-core:0.9.1 declares an API of a component:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
          - Variant 'releaseRuntimeElements-published' capability dev.icerock.moko:mvvm-core:0.9.1 declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'


![Screen Shot 2021-01-26 at 10 45 09](https://user-images.githubusercontent.com/48884950/105853103-170eb280-5fc4-11eb-9185-d81cae3a9529.png)
![Screen Shot 2021-01-26 at 10 45 55](https://user-images.githubusercontent.com/48884950/105853111-183fdf80-5fc4-11eb-96f1-15a8515b72bd.png)
![Screen Shot 2021-01-26 at 10 46 27](https://user-images.githubusercontent.com/48884950/105853117-18d87600-5fc4-11eb-9dc5-4e0b6affa3fc.png)
![Screen Shot 2021-01-26 at 10 46 57](https://user-images.githubusercontent.com/48884950/105853120-19710c80-5fc4-11eb-855c-2e2999f81d30.png)

**Comment by Alex009** [comment]
you use target `jvm` but `moko-mvvm` supports only android & ios targets for now.
you can separate mobile targets from jvm by creating additional sourceset for example `mobileMain` like this - https://github.com/icerockdev/moko-resources/issues/133#issuecomment-740700058

**Comment by joavilati** [comment]
Thank you! When i tried this  and gradle got the libraries, but now I can not use on code.

*.shared.viewmodel

![image](https://user-images.githubusercontent.com/48884950/105874608-880d9480-5fdb-11eb-9dc6-f4f6ce7cd682.png)
![image](https://user-images.githubusercontent.com/48884950/105874637-9196fc80-5fdb-11eb-8973-6ae490fb958c.png)

**Comment by joavilati** [comment]
I chose to remove the jvm as target, and that solved. Thank you for your help
