### ISSUE TITLE
Error when first time compile

### ISSUE THREAD

**Issue by irfanirawansukirman** [icerockdev/moko-mvvm#130]
A problem occurred configuring project ':mvvm-databinding'.
> Failed to notify project evaluation listener.
   > SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/irfanirawansukirman/AndroidStudioProjects/moko-mvvm/local.properties'.
   > SoftwareComponentInternal with name 'release' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

How to solve the problem?

**Comment by Alex009** [comment]
Hi!
Open project from Android studio or set environment variable with path to Android sdk
