### ISSUE TITLE
WARN: Setting the fragment as the LifecycleOwner might cause memory leaks because views lives shorter than the Fragment. Consider using Fragment's view lifecycle

### ISSUE THREAD

**Issue by vevar** [icerockdev/moko-mvvm#155]
https://github.com/icerockdev/moko-mvvm/blob/b6f2630df03bbd405e5659d85ea7df03f38e5dc7/mvvm-databinding/src/main/kotlin/dev/icerock/moko/mvvm/MvvmFragment.kt#L46

Maybe, will be better: 
`binding.lifecycleOwner = viewLifecycleOwner`

**Comment by Alex009** [comment]
yes, make sense

**Comment by Kwesi-Welbred** [comment]
yeah..that works fine.

**Comment by Alex009** [comment]
will be available in 0.12.0
