### ISSUE TITLE
Error building mokoMvvmFlowSwiftUI on newest xcode

### ISSUE THREAD

**Issue by teewhydope** [icerockdev/moko-mvvm#186]
Failed to build module 'mokoMvvmFlowSwiftUI'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)', while this compiler is 'Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)'). Please select a toolchain which matches the SDK.

**Comment by GadgeurX** [comment]
Hello. Any update on this issue? I have the same problem :(

**Comment by Alex009** [comment]
while we not fix support of swift sdk in any future swift versions - you can just copy this swift files https://github.com/icerockdev/moko-mvvm/tree/master/mvvm-flow/apple/xcode/mokoMvvmFlowSwiftUI inside your project. and remove mokoMvvmFlowSwiftUI cocoapod

**Comment by Alex009** [comment]
i update sample https://github.com/Alex009/moko-mvvm-compose-swiftui/commit/df9e5a601cbc514b7a14d049e27babfe1a697dc5 and try build on xcode 14.1 - all works fine. so i think issue is resolved
