### ISSUE TITLE
support koin viewModel 

### ISSUE THREAD

**Issue by periva101** [icerockdev/moko-mvvm#189]
Let's say that I have this ViewModel 

common using [moko-mvvm](https://github.com/icerockdev/moko-mvvm)
```
class UserBookingViewModel : ViewModel() {
    private val _state = MutableStateFlow<State>(State.Loading)
    val state: CStateFlow<State> get() = _state.cStateFlow()

}
```

I want this viewmodel to be injected using KOIN 
android app 
```
   viewModel <UserBookingViewModel> {
    UserBookingViewModel()
    }
```
**KOIN does not know about the** [moko-mvvm](https://github.com/icerockdev/moko-mvvm)
Type mismatch.
Required:
ViewModel
Found:
UserBookingViewModel

**any help on this  ,  [moko-mvvm](https://github.com/icerockdev/moko-mvvm) should support KOIN and let the android app know about the types**

**Comment by enoler** [comment]
Hello @periva101 , did you find any solution for that?

**Comment by shamshadpattani** [comment]
any update ?
