### ISSUE TITLE
Unable to use viewModel with Koin (ViewModel error from composable)

### ISSUE THREAD

**Issue by sodiqOladeni** [icerockdev/moko-mvvm#203]
I got this compile time error after adding `viewModel()` to the composable, this declaration in composable.
- viewModel: EmailInputScreenViewModel = viewModel()

Cannot access 'dev.icerock.moko.mvvm.viewmodel.ViewModel' which is a supertype of 'com.apppackage.viewmodel.ftue.EmailInputScreenViewModel'. Check your module classpath for missing or conflicting dependencies

Is there any sample project that uses Moko-Viewmodel + Koin + Compose, Is there any other thind 

![Screenshot 2022-09-13 at 5 47 33 PM](https://user-images.githubusercontent.com/106665710/189960403-c58377b1-4ff9-4212-8092-7cf5cd5b3a2a.png)

**Comment by Alex009** [comment]
change `implementation` to `api`
