### ISSUE TITLE
Remove `viewModelScope` protection

### ISSUE THREAD

**Issue by casvanluijtelaar** [icerockdev/moko-mvvm#206]
Is there a specific reason why [viewModelScope](https://github.com/icerockdev/moko-mvvm/blob/master/mvvm-core/src/commonMain/kotlin/dev/icerock/moko/mvvm/viewmodel/ViewModel.kt) is protected in your implementation? it prevents us from adding our own extensions similar to [this](https://betterprogramming.pub/all-you-need-for-mvi-is-kotlin-how-to-reduce-without-reducer-5e986856610f).

**Comment by idan-fido** [comment]
+1 needed extension fun

**Comment by Alex009** [comment]
will be available in 0.15.0 release
