### ISSUE TITLE
ViewModel calls init block, functions two times when they are called from screen

### ISSUE THREAD

**Issue by Mukhammaddin6567** [icerockdev/moko-mvvm#225]
Hi, Moko team.
I got the issue. It is when i call view model , its init block called twice. then when i use one of the functions inside viewmodel it works twice too

**Comment by Alex009** [comment]
hi. i think you have two instances of same viewmodel class. just add `println("vm: $this") to see that it's not same object

**Comment by Mukhammaddin6567** [comment]
@Alex009 objects are the same. I already did it

**Comment by Alex009** [comment]
init block can't be called twice in one object. it's kotlin behaviour, not library.
can you prepare sample repository with this bug?

**Comment by Mukhammaddin6567** [comment]
@Alex009 okay I will do it as soon as possible

**Comment by Mukhammaddin6567** [comment]
we're providing viewmodel through koin... can this be due to koin? Do you have sample usage with koin?

**Comment by Mukhammaddin6567** [comment]
https://github.com/jakhongirmadaminov/supply-kmm

this is sample repository. it starts with customers screen.

**Comment by Mukhammaddin6567** [comment]
please check branch "moko" the sample repository is in it

**Comment by Mukhammaddin6567** [comment]
@Alex009 Hi. Can you check your gmail?

**Comment by Alex009** [comment]
@Mukhammaddin6567 i check my email but not see any mails. are you send something?
did you found reason of bug?

**Comment by Mukhammaddin6567** [comment]
@Alex009 Hi. I found what is the problem. it's not related to moko-mvvm.

**Comment by Mukhammaddin6567** [comment]
@Alex009 yes I found reason of bug. It was ktor problem
