### ISSUE TITLE
Coroutines flow as reactive value holders

### ISSUE THREAD

**Issue by vchernyshov** [icerockdev/moko-mvvm#39]
Why you don't use coroutines flow to implement reactive value holders instead of LiveData?

I mean something like this:
State: https://gist.github.com/vchernyshov/d661e153e768915c5a2b3a23a7338b1c
ViewModel: https://gist.github.com/vchernyshov/cfd39b16b6e022188b97887f3f4c3351

**Comment by Alex009** [comment]
hi!
we just using LiveData approach long time, before start use coroutines :) 
your suggestion is good. I will add it to lib

**Comment by vchernyshov** [comment]
@Alex009 As I understood correct Flow based approach can replace LiveData and simplify implementation as no need to create separate LiveData class for iOS. I Have tried to modify your sample with State it works but Flow class can't be recognised at Xcode project.

**Comment by Alex009** [comment]
what do you mean "Flow class can't be recognised at Xcode"? are you try use export coroutines dependency? 
https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#exporting-dependencies-to-binaries
Flow as class should be recognised at Xcode. Problem can be only with `suspend` functions and blocks - they now will be deleted from header of framework

**Comment by NahroTo** [comment]
I think this is relevant: https://github.com/Kotlin/kotlinx.coroutines/pull/1354. Looks like the coroutines team is already busy with a Flow that holds a data.

**Comment by vchernyshov** [comment]
@NahroTo As I understood it is only lightweight version on channel. And it is a good approach to have wrapper around it, you can change internals and external API will be the same

**Comment by vchernyshov** [comment]
@Alex009 Maybe it is connected with with suspend function

**Comment by NahroTo** [comment]
Kotlin coroutines 1.3.6 introduces StateFlow, which is a reactive coroutine value holder. I think we can close this issue. Check it out: https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.3.6

**Comment by Alex009** [comment]
as already said - https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.3.6 have StateFlow with implementation of idea from this issue.
issue can be closed
