### ISSUE TITLE
Use MutableLiveData with Model

### ISSUE THREAD

**Issue by Diy2210** [icerockdev/moko-mvvm#49]
I try use MutableLiveData with Model, but it not work for me.
My Model:
![Снимок экрана 2020-07-01 в 16 31 03](https://user-images.githubusercontent.com/9552501/86249981-a8e24880-bbb8-11ea-8935-dce64be80142.png)

My Screen Model:
![Снимок экрана 2020-07-01 в 16 30 44](https://user-images.githubusercontent.com/9552501/86250002-b3044700-bbb8-11ea-8ef9-c99e015d2b63.png)
![Снимок экрана 2020-07-01 в 16 30 53](https://user-images.githubusercontent.com/9552501/86250028-bac3eb80-bbb8-11ea-8982-fa759e05a1d0.png)

And use in Screen:
![Снимок экрана 2020-07-01 в 16 31 40](https://user-images.githubusercontent.com/9552501/86250069-c9120780-bbb8-11ea-9fec-0315b7bbccb5.png)

And I dont understand how use MutableLiveData type - Int. I try get value like this:
![Снимок экрана 2020-07-01 в 16 31 50](https://user-images.githubusercontent.com/9552501/86250255-05456800-bbb9-11ea-8919-9c87e8c5529a.png)

But its not work:
![Снимок экрана 2020-07-01 в 16 32 02](https://user-images.githubusercontent.com/9552501/86250301-15f5de00-bbb9-11ea-9313-913cd6aed932.png)

And one more question, how use MutableLiveData type Array<String>.

**Comment by DevTchernov** [comment]
`text = const ...`
There шы should be something like:
`text = viewModel.updates.map{"Available: $it"}`

**Comment by Diy2210** [comment]
text = viewModel.updates.map{"Available: $it"} - dont work, with 
val updates: LiveData<**String**> = _updates.map { it.toString() }
because **text widget** implement only LiveData<**StringDesc**>.
I try put **Int value**.

**Comment by Diy2210** [comment]
> `text = const ...`
> There is should be something like:
> `text = viewModel.updates.map{"Available: $it"}`
Tnx!
And one more question, how use MutableLiveData type Array(String)

**Comment by Alex009** [comment]
`LiveData` and `MutableLiveData` is just reactive data holders. 
you can create LiveData with List, or Array of strings code:
```
private val _updates: MutableLiveData<List<String>> = MutableLiveData(emptyList())
val updates: LiveData<List<String>> = _updates
```

and later you can map it to any other value. for example if you want show count of items, do:
```
val updatesCount: LiveData<Int> = updates.map { list: List<String> -> 
    list.count 
}
```
or if you want join string:
```
val updatesString: LiveData<String> = updates.map { list: List<String> -> 
    list.joinToString()
}
```

to change value you just set value in `MutableLiveData`:
```
_updates.value = listOf("first", "second")
```
to listen changes you can use:
```
updates.addObserver { data ->
    println("data: $data")
}
```
it called in each widget

**Comment by Diy2210** [comment]
**_Awesome, tnx!_**
