### ISSUE TITLE
Installation does not work, "could not find method androidMainImplementation() for arguments..."

### ISSUE THREAD

**Issue by Berki2021** [icerockdev/moko-mvvm#56]
Hello, I am trying to implement your library, but it does not work.

Here is the strack trace:

A problem occurred evaluating project ':app'.
> Could not find method androidMainImplementation() for arguments [androidx.lifecycle:lifecycle-extensions:2.1.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by Alex009** [comment]
Hello!
I think your module :app is not multiplatform module, so in :app you should connect dependency with `implementation`. `androidMainImplementation` should be used in Multiplatform module where moko-mvm connected
