### ISSUE TITLE
Question: How does the ViewModel component work on iOS?

### ISSUE THREAD

**Issue by AdamSHurwitz** [icerockdev/moko-mvvm#59]
In the _[ViewModel with send events to View][example]_ example, `EventsViewModel` is implemented for the Android version as an Android component instance of _[`ViewModel`][viewmodel]_.

How does the `EventsViewModel` work for the iOS version since it cannot implement the same Android component instance of `ViewModel`? Is there an alternative implementation of `ViewModel` defined to run for iOS?

[example]: https://github.com/icerockdev/moko-mvvm#viewmodel-with-send-events-to-view
[viewmodel]: https://developer.android.com/topic/libraries/architecture/viewmodel

**Comment by Alex009** [comment]
hi!
ViewModel is **expect** class - https://github.com/icerockdev/moko-mvvm/blob/master/mvvm/src/commonMain/kotlin/dev/icerock/moko/mvvm/viewmodel/ViewModel.kt

actual implementation on android is subclass of android's ViewModel - https://github.com/icerockdev/moko-mvvm/blob/master/mvvm/src/androidMain/kotlin/dev/icerock/moko/mvvm/viewmodel/ViewModel.kt as you already see.

actual implementation on ios is just class - https://github.com/icerockdev/moko-mvvm/blob/master/mvvm/src/iosMain/kotlin/dev/icerock/moko/mvvm/viewmodel/ViewModel.kt

info about expect/actual - https://kotlinlang.org/docs/reference/mpp-connect-to-apis.html

**Comment by AdamSHurwitz** [comment]
I understand the high-level concept now. Thanks for taking the time to share those classes and resources! 🙏🏻
