### ISSUE TITLE
No matching variant of dev.icerock.moko:mvvm:0.8.0 was found

### ISSUE THREAD

**Issue by Diy2210** [icerockdev/moko-mvvm#62]
Hi, I add moko-mvvm to multiplatform project, but when start build I get error:
**_no matching variant of dev.icerock.moko:mvvm:0.8.0 was found_**

I use kotlin: 1.4.10
build gradle: 4.0.1
gradle: 6.6
Android Studio: 4.0.1

build.gradle:
add maven url to allProjects
![1](https://user-images.githubusercontent.com/9552501/93892793-967a3580-fcf5-11ea-9a2f-2af96b8bec72.png)

Add implementation from common gradle
build.gradle.kts:
![2](https://user-images.githubusercontent.com/9552501/93893049-dd682b00-fcf5-11ea-9997-52e8ad8989b5.png)
![3](https://user-images.githubusercontent.com/9552501/93893111-f244be80-fcf5-11ea-9ecf-babe1eff6d77.png)

ViewModel without any errors:
![4](https://user-images.githubusercontent.com/9552501/93893180-04bef800-fcf6-11ea-9ae3-6f542299c5f2.png)

But I get error:
![5](https://user-images.githubusercontent.com/9552501/93893221-10122380-fcf6-11ea-8a5d-a2f096817db1.png)

**Comment by Alex009** [comment]
Hi!
Use target Android instead jvm please

**Comment by Diy2210** [comment]
Thanks for the quick response! Any example, how use it?

**Comment by Alex009** [comment]
Just clone moko-mvvm repo and see sample project

**Comment by Diy2210** [comment]
Ok, tnx!
