### ISSUE TITLE
Kotlin Multiplatform Mobile (KMM) plugin + moko-mvvm?

### ISSUE THREAD

**Issue by Diy2210** [icerockdev/moko-mvvm#63]
Hi, I try use moko-mvvm + kotlin multiplatform mobile (KMM), but it not work!
I get some error:
![1](https://user-images.githubusercontent.com/9552501/94148451-547cfb00-fe7f-11ea-8d07-48eb47b40a01.png)

![2](https://user-images.githubusercontent.com/9552501/94148475-59da4580-fe7f-11ea-9f29-67dd9d4a4895.png)
![3](https://user-images.githubusercontent.com/9552501/94148483-5cd53600-fe7f-11ea-916d-eaaa41079a77.png)
![4](https://user-images.githubusercontent.com/9552501/94148493-5e9ef980-fe7f-11ea-88f5-e15342e3488f.png)

**Comment by Alex009** [comment]
while moko-resources and mvvm not updated to 1.4.10 this lines required:
```
    // temporary fix of https://youtrack.jetbrains.com/issue/KT-41083
    commonMainImplementation("dev.icerock.moko:resources:0.13.0")
    commonMainImplementation("dev.icerock.moko:parcelize:0.4.0")
    commonMainImplementation("dev.icerock.moko:graphics:0.4.0")
```

**Comment by Diy2210** [comment]
Oh, where I do add this lines in shared build.gradle.kts?
I add it in block?
**_kotlin {
  sourceSets { ... }
}_**

![Снимок экрана 2020-09-24 в 16 33 02](https://user-images.githubusercontent.com/9552501/94152093-de2ec780-fe83-11ea-98f0-b0a49a24f768.png)

**Comment by Alex009** [comment]
@Diy2210 you can add dependencies in dependencies block out of kotlin block, or add `implementation` dependency inside `kotlin.sourceSets.commonMain.dependencies`
for example - https://github.com/icerockdev/moko-permissions/blob/master/sample/mpp-library/build.gradle.kts

**Comment by Diy2210** [comment]
I add dependencies in dependencies block out of kotlin block, sync gradle is ok. Library add External Lib, but ViewModel class dont work - Unresolved Reference :(

![Снимок экрана 2020-09-25 в 15 44 18](https://user-images.githubusercontent.com/9552501/94268776-56f65800-ff46-11ea-8c33-65d1a599d629.png)

![Снимок экрана 2020-09-25 в 15 42 04](https://user-images.githubusercontent.com/9552501/94268492-eb13ef80-ff45-11ea-8543-105ba56c94db.png)

**Comment by Alex009** [comment]
@Diy2210 you create `android` target? not `jvm`?
maybe you can show project? i can try it and find fix

**Comment by Diy2210** [comment]
I create android target, maybe I forgot something. I will be grateful for the help.
https://github.com/Diy2210/KMM

**Comment by Alex009** [comment]
@Diy2210 here PR with correct configuration of project - https://github.com/Diy2210/KMM/pull/1

**Comment by mathemandy** [comment]
This helped me, thanks !!
