### ISSUE TITLE
Error Cannot access ViewModel

### ISSUE THREAD

**Issue by Diy2210** [icerockdev/moko-mvvm#64]
I get some error: **_Cannot access 'dev.icerock.moko.mvvm.viewmodel.ViewModel' which is a supertype of 'net.compoza.deactivator.mpp.model.ListViewModel'. Check your module classpath for missing or conflicting dependencies._**

ViewModel class:
![Снимок экрана 2020-09-29 в 12 32 27](https://user-images.githubusercontent.com/9552501/94541159-ec982d00-024f-11eb-9a8e-f8e34a0b71ca.png)

Fragment code:
![Снимок экрана 2020-09-29 в 12 32 07](https://user-images.githubusercontent.com/9552501/94541202-fae64900-024f-11eb-91bb-730cce15d478.png)

shared build.gradle:
![Снимок экрана 2020-09-29 в 12 36 11](https://user-images.githubusercontent.com/9552501/94541573-692b0b80-0250-11eb-925c-84d7f664a3cd.png)
![Снимок экрана 2020-09-29 в 12 36 20](https://user-images.githubusercontent.com/9552501/94541583-6c25fc00-0250-11eb-85fc-404c7c53c109.png)

I use:
Android Studio: 4.0.1
Kotlin: 1.4.10
gradle: 6.6
build.gradle: 4.0.1
And block Android() in shared build.gradle.

**Comment by Alex009** [comment]
Lifecycle extensions should be Android dependency, not common.

See readme setup block

**Comment by Diy2210** [comment]
I move lifecycle extensions to android dependency, but error dont gone.
**_Cannot access 'dev.icerock.moko.mvvm.viewmodel.ViewModel'_**

**_error: cannot generate view binders com.sun.tools.javac.code.Symbol$CompletionFailure: class file for dev.icerock.moko.mvvm.viewmodel.ViewModel not found_**

build.gradle:
![Снимок экрана 2020-09-29 в 12 50 09](https://user-images.githubusercontent.com/9552501/94543190-66311a80-0252-11eb-89da-afc9f97df63c.png)

**Comment by Diy2210** [comment]
Dependency Android:
![Снимок экрана 2020-09-29 в 12 59 34](https://user-images.githubusercontent.com/9552501/94544315-c3799b80-0253-11eb-9b77-d25c05ea8ae0.png)

Dependency Shared:
![Снимок экрана 2020-09-29 в 12 59 44](https://user-images.githubusercontent.com/9552501/94544360-cffdf400-0253-11eb-997c-96e9d73e0a8f.png)

![Снимок экрана 2020-09-29 в 13 01 11](https://user-images.githubusercontent.com/9552501/94544414-dee4a680-0253-11eb-935e-3d630421b160.png)

**Comment by Alex009** [comment]
now problem with databinding logic. try change `implementation` to `api` dependency definition of moko-mvvm. or add moko-mvvm to `app` module dependencies directly

**Comment by urgentx** [comment]
Change your commonMain moko-mvvm dependency declaration from `implementation` to `api`
