### ISSUE TITLE
Can I have a custom name for library?

### ISSUE THREAD

**Issue by AlexeySobolevskiy** [icerockdev/moko-mvvm#66]
Hi!

I'm trying to integrate moko-mvvm for iOS. Unfortunately, integration instructions are not clear for me. In commercial project we have Kotlin Native Multiplatform engine for several years. On Kotlin side everything is fine, but in iOS I'm unsuccessfully trying to just install moko and have its classes in Xcode. Is it strictly required to have a name "MultiPlatformLibrary" and "mpp-library" for builded framework? This how it is in example iOS project:
https://github.com/icerockdev/moko-mvvm/blob/master/sample/ios-app/Podfile

**Comment by Alex009** [comment]
hi!
iOS additions cocapod `MultiPlatformLibraryMvvm` require that kotlin framework should be named `MultiPlatformLibrary`. It's required to import kotlin classes in cocoapod - https://github.com/icerockdev/moko-mvvm/blob/master/mvvm/src/iosMain/swift/Core/UILabel%2BLiveData.swift#L6

if you not use `MultiPlatformLibraryMvvm` cocoapod in iOS - you can set any name for kotlin framework.
Or you can copy-paste all code from https://github.com/icerockdev/moko-mvvm/tree/master/mvvm/src/iosMain/swift directly to your project and replace `import MultiPlatformLibrary` to `import YourKotlinFrameworkName`

**Comment by AlexeySobolevskiy** [comment]
@Alex009 

Thank you very much! Unfortunately, I need exactly MultiPlatformLibraryMvvm :) I will try with requested solutions
