### ISSUE TITLE
[Feature Request] Split project into multiple artifacts

### ISSUE THREAD

**Issue by nrobi144** [icerockdev/moko-mvvm#79]
I'd propose the following changes in order to better capture the possible needs of consumers:

1. Since Android is moving towards Flows ([StateFlow & SharedFlow](https://developer.android.com/kotlin/flow/stateflow-and-sharedflow)), I believe it would make sense to have a separate `-livedata` artifact
2. Also with moving towards compose I think the `MvvmActivity` and binding adapters could also go into a separate artifact
3. For those who are sharing VM logic & would like to leverage the Android Arch Viewmodel, a lightweight artifact, with the Android VM abstraction, which targets all possible KMP platforms (js, macos, jvm, etc...) would be really beneficial

**Comment by Tetraquark** [comment]
It seems that the similar idea is already being discussed in #65
