### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by SebastianPeredoM** [icerockdev/moko-mvvm#81]
Hi. When building I have this error

Could not determine the dependencies of task ':shared:compileKotlinMetadata'.
> Couldn't resolve metadata artifact for ModuleDependencyIdentifier(groupId=dev.icerock.moko, moduleId=resources) in configuration ':shared:iosArm64CompileKlibraries'

![Screen Shot 2020-12-07 at 23 03 10](https://user-images.githubusercontent.com/29511805/101438462-6992f300-38e0-11eb-8e08-f3346c2edb6f.png)

**Comment by Alex009** [comment]
hi @SebastianPeredoM !
please use workaround for now:
https://github.com/icerockdev/moko-mvvm/issues/63#issuecomment-698342092

when we release next version with kotlin 1.4.21 - this workaround will not be required

**Comment by Alex009** [comment]
workaround not needed after 0.8.1 release
