### ISSUE TITLE
trying to share android ViewModels (+Databinding and Navhostfragment)

### ISSUE THREAD

**Issue by hlnstepanova** [icerockdev/moko-mvvm#84]
Hi Alex,

I'm trying to rewrite my android ViewModels into shared ViewModels, but cannot manage to get it working.
I started with LoginViewModel, which is similar to the one in samples. But in my app I use MainActivity with NavHostFragment and Databinding for navigation drawer.
Here is my code. Unfortunately I cannot share the project, but I made gists for all relevant files.

[MainActivity.kt](https://gist.github.com/hlnstepanova/667994e183c17c7d7789dd6b3ea782ec)
[activity_main.xml](https://gist.github.com/hlnstepanova/eda7420ce56da996f1453c7656ae1ee3)
[nav_header.xml](https://gist.github.com/hlnstepanova/fb57fad2bb22d5128a25308405d19448)
[LoginModel.kt](https://gist.github.com/hlnstepanova/f0056013dd99c0f90a8704369ee3275f)
[BaseFragment.kt](https://gist.github.com/hlnstepanova/75c7ea27ddc7720eb0744ef31c2c1569)
[LoginFragment.kt](https://gist.github.com/hlnstepanova/f52b39b506ed55dff0ae7bf81ca65cb2)
[fragment_login.xml](https://gist.github.com/hlnstepanova/8a3801623eacad82beeeac07fcd940cf)

When I clean and build the project, it builds successfully and runs in the emulator.

Then, I see my main activity with login fragment and try to login. When clicking on the login button, LoginModel seems to dispatch the login event which should redirect to the next screen, but nothing happens. I assume I'm doing something wrong when binding the event listener. I was also not sure, whether I have to implement MvvmEventsFragment instead of Fragment() or how I could do it in this case.

```
 <Button
                android:id="@+id/loginBtn"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="@string/login"
                android:onClick="@{() -> viewModel.onLogin()}"
                android:layout_marginVertical="@dimen/large_margin"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@id/LlLogin" />
```

```
fun onLogin() {
        val user = User(username.value, password.value)

        // regardless of login type (cloud or local), validate username and password
        validateUserData(user)?.let {
            eventsDispatcher.dispatchEvent { showError(it) }
            return
        }

        // if cloud login, try login with api
        if (cloudLogin.value) {
            viewModelScope.launch {
                startLoading()
                login(user)?.let { errorString ->
                    eventsDispatcher.dispatchEvent { showError(errorString) }
                    stopLoading()
                    return@launch
                }
                eventsDispatcher.dispatchEvent { navigateToDeviceList(username.value)}
                setLogged(true)
            }
        } else {
            // if local login, validate ip
            validateIpData(url.value)?.let {
                eventsDispatcher.dispatchEvent { showError(it) }
                return
            }
            eventsDispatcher.dispatchEvent { navigateToFavouritesList(url.value)}
            setLogged(true)
        }


    }
```

I would really appreciate any help.

**Comment by hlnstepanova** [comment]
I managed to go to the next screen by getting rid of BaseFragment and using MvvmFragment for LoginFragment, as well as changing some parts in MainActivity and LoginModel
[LoginFragment](https://gist.github.com/hlnstepanova/efdef6849be5d535f35e327406b01216)
[MainActivity](https://gist.github.com/hlnstepanova/759722efad9cd7edddc87da27c1fabc4)
[LoginModel](https://gist.github.com/hlnstepanova/1dabb07ce34d9d927be54074ad701b8c)

**Comment by Alex009** [comment]
hi! sorry for late reply.
if problem actual reproducer project will be very helpful. 
as i understand you try to use EventsDispatcher with simple Fragment, without extends MvvmEventsFragment. 
to use EventsDispatcher you should bind to lifecycle at your Fragment. as here - https://github.com/icerockdev/moko-mvvm#android-1
or here - https://github.com/icerockdev/moko-mvvm/blob/master/mvvm-databinding/src/main/kotlin/dev/icerock/moko/mvvm/MvvmEventsFragment.kt#L18

**Comment by hlnstepanova** [comment]
Using MvvmEventsFragment was the solution
