### ISSUE TITLE
Should we implement MutableLiveData constructor without argument ? 

### ISSUE THREAD

**Issue by theGlenn** [icerockdev/moko-mvvm#87]
I was wondering why [MutableLiveData](https://github.com/icerockdev/moko-mvvm/blob/master/mvvm/src/androidMain/kotlin/dev/icerock/moko/mvvm/livedata/MutableLiveData.kt) doesn't also implements the argument-less constructor. `new MutableLiveDate<Type>()`

**Comment by Alex009** [comment]
hi! here i already answer about this request https://github.com/icerockdev/moko-mvvm/issues/52#issuecomment-657943326
and analog of `LiveData` - `StateFlow` also require initial value argument - https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-state-flow/
